-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 09:49:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CulDampollaDiagram
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CulDampollaDiagram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CulDampollaDiagram` DEFAULT CHARACTER SET utf8 ;
USE `CulDampollaDiagram` ;

-- -----------------------------------------------------
-- Table `CulDampollaDiagram`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampollaDiagram`.`Glasses` (
  `idGlasses` INT NOT NULL AUTO_INCREMENT,
  `Brand` VARCHAR(45) NOT NULL,
  `leftGrad` DECIMAL NOT NULL,
  `rightGrad` DECIMAL NOT NULL,
  `mount` ENUM('pasta', 'flotante', 'metal') NOT NULL,
  `mountColor` VARCHAR(20) NULL,
  `leftColor` VARCHAR(20) NOT NULL,
  `rightColor` VARCHAR(20) NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`idGlasses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampollaDiagram`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampollaDiagram`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `supplierName` VARCHAR(45) NOT NULL,
  `supplierCity` VARCHAR(45) NOT NULL,
  `supplierStreet` VARCHAR(45) NOT NULL,
  `supplierStreetNum` INT NULL,
  `supplierDoorNum` INT NULL,
  `supplierPC` INT(5) NOT NULL,
  `supplierCountry` VARCHAR(45) NULL,
  `phone` INT(12) NULL,
  `fax` INT NULL,
  `CIF` VARCHAR(10) NOT NULL,
  `Glasses_idGlasses` INT NOT NULL,
  PRIMARY KEY (`idSupplier`),
  INDEX `fk_Supplier_Glasses_idx` (`Glasses_idGlasses` ASC),
  CONSTRAINT `fk_Supplier_Glasses`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `CulDampollaDiagram`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampollaDiagram`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampollaDiagram`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `clientName` VARCHAR(45) NOT NULL,
  `clientPC` INT(5) NOT NULL,
  `clientEmail` CHAR(30) NOT NULL,
  `registerDate` DATE NOT NULL,
  `recomendedFrom` INT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampollaDiagram`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampollaDiagram`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `salary` INT NULL,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CulDampollaDiagram`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CulDampollaDiagram`.`Invoice` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NULL,
  `idGlasses` INT NULL,
  `idEmployee` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idInvoice`),
  INDEX `idClient_idx` (`idClient` ASC),
  INDEX `idGlasses_idx` (`idGlasses` ASC),
  INDEX `idEmployee_idx` (`idEmployee` ASC),
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `CulDampollaDiagram`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGlasses`
    FOREIGN KEY (`idGlasses`)
    REFERENCES `CulDampollaDiagram`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `CulDampollaDiagram`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
